#Faça um algoritmo que calcule e mostre a tabuada de um número digitado pelo usuário.
numero = int (input("Digite um número para ver a tabuada;"))
print (f"1 x {numero} = {numero * 1}")
print (f"2 x {numero} = {numero * 2}")
print (f"3 x {numero} = {numero * 3}")
print (f"4 x {numero} = {numero * 4}")
print (f"5 x {numero} = {numero * 5}")
print (f"6 x {numero} = {numero * 6}")
print (f"7 x {numero} = {numero * 7}")
print (f"8 x {numero} = {numero * 8}")
print (f"9 x {numero} = {numero * 9}")
print (f"10 x {numero} = {numero * 10}")
